### ISSUE TITLE
[Question]: Could you please clarify the Sikuli dlls

### ISSUE THREAD

**Issue by anupamdas24** [uttesh/selenium-flash-testng#1]
Hello Uttesh,

Greetings!

Could you please let me know how to find the sikuli dlls. I am not able to locate them in the package.

**Comment by uttesh** [comment]
Hi Anupam,

 Its been long back i don't remember much, but dll is not required with jar
also you can execute.

what is the reason behind choosing sikuli?

Thanks,
Uttesh

**Comment by anupamdas24** [comment]
Hello Uttesh,

We have the Canvas application where we need to perform the drag and drop operation. Sikuli is the only option as of now for me as I have tried to use Action Builder, Robot class etc, but no luck.
If you know some other tools, please help.
Also I could able to figure out for the sikuli dlls, so we can close this issue.

**Comment by uttesh** [comment]
@anupamdas24 
  Please do attach the dll file or links to download the dll, which may help other.
Thanks,
